import type { WaveConfig } from "../types/wave";

export const WAVES: WaveConfig[] = [
  {
    spawnInterval: 600,
    enemies: ["Slime1", "Slime1", "Slime1", "Slime1", "Slime1"],
  },
  {
    spawnInterval: 600,
    enemies: [
      "Slime1",
      "Slime1",
      "Slime1",
      "Slime1",
      "Slime1",
      "Slime1",
      "Slime1",
      "Slime1",
      "Slime2",
      "Slime2",
    ],
  },
  {
    spawnInterval: 600,
    enemies: [
      "Slime1",
      "Slime1",
      "Slime1",
      "Slime1",
      "Slime1",
      "Slime1",
      "Slime1",
      "Slime1",
      "Slime1",
      "Slime1",
      "Slime2",
      "Slime2",
      "Slime2",
      "Slime2",
      "Slime2",
    ],
  },
  {
    spawnInterval: 500,
    enemies: [
      "Slime1",
      "Slime1",
      "Slime1",
      "Slime1",
      "Slime1",
      "Slime1",
      "Slime1",
      "Slime1",
      "Slime1",
      "Slime1",
      "Slime2",
      "Slime2",
      "Slime2",
      "Slime2",
      "Slime2",
      "Slime2",
      "Slime3",
    ],
  },
  {
    spawnInterval: 500,
    enemies: [
      "Slime1",
      "Slime1",
      "Slime1",
      "Slime1",
      "Slime1",
      "Slime1",
      "Slime1",
      "Slime1",
      "Slime2",
      "Slime2",
      "Slime2",
      "Slime2",
      "Slime2",
      "Slime2",
      "Slime2",
      "Slime2",
      "Slime3",
      "Slime3",
      "Slime3",
      "Tank",
    ],
  },
  {
    spawnInterval: 500,
    enemies: [
      "Slime2",
      "Slime2",
      "Slime2",
      "Slime2",
      "Slime2",
      "Slime2",
      "Slime3",
      "Slime3",
      "Slime3",
      "Slime3",
      "Slime3",
      "Slime3",
      "Slime3",
      "Slime3",
      "Slime4",
      "Slime4",
      "Tank",
      "Tank",
    ],
  },
  {
    spawnInterval: 450,
    enemies: [
      "Slime2",
      "Slime2",
      "Slime2",
      "Slime2",
      "Slime2",
      "Slime3",
      "Slime3",
      "Slime3",
      "Slime3",
      "Slime3",
      "Slime3",
      "Slime3",
      "Slime3",
      "Slime3",
      "Slime3",
      "Slime4",
      "Slime4",
      "Slime4",
      "Slime4",
      "Tank",
      "Tank",
      "Tank",
    ],
  },
  {
    spawnInterval: 450,
    enemies: [
      "Slime3",
      "Slime3",
      "Slime3",
      "Slime3",
      "Slime4",
      "Slime4",
      "Slime4",
      "Slime4",
      "Slime4",
      "Slime4",
      "Slime4",
      "Slime4",
      "Slime4",
      "Slime4",
      "Slime5",
      "Slime5",
      "Slime5",
      "Tank",
      "Tank",
      "Tank",
      "Tank",
    ],
  },
  {
    spawnInterval: 400,
    enemies: [
      "Slime3",
      "Slime3",
      "Slime3",
      "Slime4",
      "Slime4",
      "Slime4",
      "Slime4",
      "Slime4",
      "Slime4",
      "Slime4",
      "Slime4",
      "Slime5",
      "Slime5",
      "Slime5",
      "Slime5",
      "Slime5",
      "Tank",
      "Tank",
      "Tank",
      "Tank",
      "Tank",
      "Tank",
    ],
  },
  {
    spawnInterval: 350,
    enemies: [
      "Slime4",
      "Slime4",
      "Slime4",
      "Slime4",
      "Slime4",
      "Slime4",
      "Slime5",
      "Slime5",
      "Slime5",
      "Slime5",
      "Slime5",
      "Slime5",
      "Slime5",
      "Slime5",
      "Slime5",
      "Slime5",
      "Tank",
      "Tank",
      "Tank",
      "Tank",
      "Tank",
      "Tank",
      "Tank",
      "Tank",
    ],
  },
];
